# -*- coding: utf-8 -*-
"""day3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zzw02Vf6Ttomvag8SJ8rRW-PTyGPNpyS
"""

print("Hello, Excited to start Data Science.")

customer_name = "John Doe"
customer_age = 28
customer_balance = 120.75
print("Customer:", customer_name)
print("Age:", customer_age)
print("Balance:", customer_balance)

product_price = 200
discount = product_price * 0.10 # 10% discount
final_price = product_price - discount
print("Final Price after Discount:", final_price)

import numpy as np
sales = np.array([150, 200, 250, 300, 400, 350, 500])
print("Sales Data:", sales)

print("Average Sales:", np.mean(sales))
print("Highest Sale:", np.max(sales))
print("Lowest Sale:", np.min(sales))

import pandas as pd
data = {
"Customer": ["Alice", "Bob", "Charlie"],
"Age": [25, 30, 35],
"Amount Spent": [120, 200, 150]
}
df = pd.DataFrame(data)
print(df)

from google.colab import files
uploaded = files.upload() # Upload your CSV file
df = pd.read_csv("customer_data.csv") # Replace with your file name
df.head()